# Generated by Django 4.0.6 on 2022-08-02 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='name_wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wallet.customer'),
        ),
    ]
