# Generated by Django 4.0.6 on 2022-08-31 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='origin_acc',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='origin_acc', to='wallet.customer'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='destination_acc',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_acc', to='wallet.customer'),
        ),
    ]
