# Generated by Django 4.0.6 on 2022-09-01 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_transactions_origin_acc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receipt',
            name='receipt_name',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
